{{- range .Values.authorizationPolicy }}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ default $.Release.Name .name }}
  namespace: {{ default $.Release.Namespace $.Values.namespace }}
  labels:
    {{- include "istio-resources.labels" $ | nindent 4 }}
  {{- with $.Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if include "istio-resources.hasSpec" . }}
spec:
  {{- toYaml .spec | nindent 2 }}
{{- else }}
spec:
  {{- if .selector }}
  selector:
    {{- toYaml .selector | nindent 4 }}
  {{- end }}
  {{- if .targetRefs }}
  targetRefs:
    {{- toYaml .targetRefs | nindent 4 }}
  {{- end }}
  {{- if .action }}
  action: {{ .action }}
  {{- end }}
  {{- if .rules }}
  rules:
    {{- toYaml .rules | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
