{{- range .Values.destinationrule }}
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ default $.Release.Name .name }}-destinationrule
  namespace: {{ default $.Release.Namespace $.Values.namespace }}
  labels:
    {{- include "istio-resources.labels" $ | nindent 4 }}
  {{- with $.Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if include "istio-resources.hasSpec" . }}
  {{- toYaml .spec | nindent 2 }}
{{- else }}
  host: {{ .host }}
{{- with .exportTo }}
  exportTo:
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- with .workloadSelector }}
  workloadSelector:
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- if .trafficPolicy }}
  trafficPolicy:
    {{- toYaml .trafficPolicy | nindent 4 }}
{{- end }}
{{- if .subsets }}
  subsets:
    {{- toYaml .subsets | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
