{{- range .Values.egress }}
{{- $egress := . }}
{{- $config := include "istio-resources.egressConfig" . | fromYaml }}
{{- range .gateways }}
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ default $.Release.Name $egress.name }}-gateway-{{ .type }}
  namespace: {{ default $.Release.Namespace $.Values.namespace }}
  labels:
    {{- include "istio-resources.labels" $ | nindent 4 }}
  {{- with $.Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if include "istio-resources.hasSpec" . }}
  {{- toYaml .spec | nindent 2 }}
{{- else }}
  selector:
    app: {{ .gateway_selector }}
  servers:
    {{- range $config.ports }}
    - port:
        number: {{ .number }}
        name: {{ .name }}
        protocol: {{ .protocol }}
    {{- if or (eq .protocol "TLS") (eq .protocol "HTTPS") }}
      tls:
        mode: PASSTHROUGH
    {{- end }}
      hosts:
        {{- toYaml $config.hosts | nindent 8 }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
