{{- range .Values.egress }}
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: {{ default $.Release.Name .name }}-egress
  namespace: {{ default $.Release.Namespace $.Values.namespace }}
  labels:
    {{- include "istio-resources.labels" $ | nindent 4 }}
  {{- with $.Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if include "istio-resources.hasSpec" . }}
  {{- toYaml .spec | nindent 2 }}
{{- else }}
  hosts:
    {{- toYaml .hosts | nindent 4 }}
  ports:
    {{- range .ports }}
    - number: {{ .number }}
      name: {{ .name }}
      protocol: {{ .protocol }}
    {{- end }}
{{- if .location }}
  location: {{ .location }}
{{- end }}
{{- if .resolution }}
  resolution: {{ .resolution }}
{{- end }}
{{- end }}
{{- end }}
