apiVersion: v2
name: istio-resources
description: A Helm chart to manage Istio resources (Gateway, VirtualService,
  ServiceEntry, DestinationRule, AuthorizationPolicy, etc.)
type: application
version: 0.3.0
appVersion: "1.0"
home: https://github.com/akopyanlabs/istio-resources
sources:
  - https://github.com/akopyanlabs/istio-resources
keywords:
  - istio
  - service-mesh
  - gateway
  - virtualservice
  - serviceentry
  - destinationrule
  - authorization
  - security
  - mtls
maintainers:
  - name: Armen Akopyan
icon: https://istio.io/latest/favicons/android-192x192.png
annotations:
  category: networking
  licenses: Apache-2.0
